const express = require('express');
const path = require('path');
const fs = require('fs');
const dotenv = require('dotenv');

// Load environment variables
dotenv.config();

const PORT = process.env.PORT || 3000;
const app = express();

// Parse JSON and URL-encoded bodies
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: true, limit: '50mb' }));

// Ensure directories exist
const dataDir = path.join(__dirname, 'data');
const uploadsDir = path.join(__dirname, 'uploads');
if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });
if (!fs.existsSync(uploadsDir)) fs.mkdirSync(uploadsDir, { recursive: true });

// Static file serving
app.use(express.static(path.join(__dirname, 'public')));
app.use('/uploads', express.static(uploadsDir));

// Import routes
const authRoutes = require('./routes/auth');
const incidentRoutes = require('./routes/incidents');
const messageRoutes = require('./routes/messages');
const alertRoutes = require('./routes/alerts');
const auditRoutes = require('./routes/audit');
const exportRoutes = require('./routes/export');

// API Routes
app.use('/api/auth', authRoutes);
app.use('/api/incidents', incidentRoutes);
app.use('/api/messages', messageRoutes);
app.use('/api/alerts', alertRoutes);
app.use('/api/audit', auditRoutes);
app.use('/api/export', exportRoutes);
app.use('/api/import', exportRoutes);

// --- Server-Sent Events (SSE) Setup ---
let sseClients = [];

app.get('/api/alerts/stream', (req, res) => {
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.flushHeaders(); // flush the headers to establish SSE

  // Tell the client we are connected
  res.write('data: {"connected": true}\n\n');

  sseClients.push(res);

  req.on('close', () => {
    sseClients = sseClients.filter(client => client !== res);
  });
});

// Listen for new alerts generated by the POST /api/alerts/simulate or periodic background task
app.on('new_alert', (alertData) => {
  sseClients.forEach(client => {
    client.write(`data: ${JSON.stringify(alertData)}\n\n`);
  });
});

// Periodic alert generation (every 15 seconds)
const db = require('./database');
setInterval(() => {
  try {
    const severities = ['low', 'medium', 'high'];
    const severity = severities[Math.floor(Math.random() * severities.length)];
    const message = `Automated safety check - Status: Normal - Severity: ${severity}`;
    const now = new Date().toISOString();

    const stmt = db.prepare('INSERT INTO alerts (message, severity, timestamp) VALUES (?, ?, ?)');
    const info = stmt.run(message, severity, now);

    const alertData = {
      id: info.lastInsertRowid,
      message,
      severity,
      timestamp: now,
      auto: true
    };

    app.emit('new_alert', alertData);
  } catch (err) {
    console.error('Failed to generate automatic alert:', err);
  }
}, 15000);
// -------------------------------------

// Catch-all route to serve the SPA
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// Start server
app.listen(PORT, () => {
  console.log(`Community Safety & Incident Tracker running on http://localhost:${PORT}`);
});
